### ISSUE TITLE
Mobile: Project name alignment

### ISSUE THREAD

**Issue by eko24ive** [naumenko-denis/Home-work#1]
![image](https://cloud.githubusercontent.com/assets/25591824/22932181/8f0c39a8-f2cf-11e6-91ff-148232897622.png)

Project name must be aligned to navigation, use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22932199/a7c1a384-f2cf-11e6-84f0-5634589e5660.png)

**Comment by naumenko-denis** [comment]
add margin-left to title
